# Generated by Django 6.0.3 on 2026-03-16 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_category_slugs(apps, schema_editor):
    Category = apps.get_model("places", "Category")
    used = set()

    for category in Category.objects.all().order_by("id"):
        base = slugify(category.name, allow_unicode=True) or f"category-{category.pk}"
        slug = base
        suffix = 2
        while slug in used:
            slug = f"{base}-{suffix}"
            suffix += 1
        Category.objects.filter(pk=category.pk).update(slug=slug)
        used.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(populate_category_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='ai_sentiment_summary',
            field=models.TextField(blank=True, help_text='Tóm tắt cảm xúc từ reviews do AI tạo ra', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Người đóng góp địa điểm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='places.place'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='Vector ngữ nghĩa (768 chiều từ PhoBERT/MiniLM)', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_hidden_gem',
            field=models.BooleanField(default=False, help_text='Địa điểm bản địa ít người biết'),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='places.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='users_bookmark',
        ),
        migrations.AlterModelTable(
            name='category',
            table='places_category',
        ),
        migrations.AlterModelTable(
            name='place',
            table='places_place',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='places_tag',
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Ảnh bìa thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'db_table': 'places_image',
            },
        ),
    ]
