# Generated by Django 6.0.3 on 2026-03-16 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_category_options_category_slug_and_more'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'place')},
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='No comment', help_text='Nội dung đánh giá'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Điểm đánh giá từ 1 đến 5 sao'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Điểm cảm xúc AI (-1 đến 1)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews_review',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
